# Ansible playbook for new user setup
#
# Run with:
#   ansible-playbook -K setup-new-user.yml
#

- hosts: 127.0.0.1
  connection: local
  
  tasks:
      - name: Install git, vim and stow
        action: >
            {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
        with_items:
            - vim
            - git
            - stow
        become: yes

      - name: Clone installations repo
        git: repo=https://@gitlab.com/wreiner/dotfiles.git dest=~/.dotfiles force=no

      - name: Check for old .bashrc
        stat: path=~/.bashrc
        register: bashrc_stat

      - name: Backup old .bashrc
        command: mv ~/.bashrc ~/.bashrc.{{ansible_date_time.date}}
        when: bashrc_stat.stat.exists and bashrc_stat.stat.isreg

      - name: stow bash
        command: stow -d ~/.dotfiles -t $HOME bash

      - name: stow vim
        command: stow -d ~/.dotfiles -t $HOME vim

      - name: Install vim plug
        command: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

      - name: Install Plugins
        command: /usr/bin/vim +PlugInstall +qall

      - name: stow git
        command: stow -d ~/.dotfiles -t $HOME git
            
      - name: stow tmux
        command: stow -d ~/.dotfiles -t $HOME tmux
            
      - name: stow ssh
        command: stow -d ~/.dotfiles -t $HOME ssh
            
      - name: stow top config
        command: stow -d ~/.dotfiles -t $HOME top
        when: ansible_distribution == "Archlinux"
            
